In [3]:
#1
import numpy
def arrays(arr):
    a=numpy.array(arr,float)
    return a[::-1]
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


In [4]:
#2
import numpy
def reshape(arr):
    a=numpy.array(arr,int)
    return numpy.reshape(a,(3,3))
arr=input().strip().split(' ')
result=reshape(arr)
print(result)  

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Function 3: Transpose and Flatten
import numpy
N, M = list(map(int, input().split()))
a = numpy.array([input().split() for _ in range(N)], int)
print(a.transpose())
print(a.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


In [6]:
# Function 4: Concatenate
import numpy
N,M,P=list(map(int,input().split()))
arr1=numpy.array([input().split() for i in range(N)],int)
arr2=numpy.array([input().split() for j in range(M)],int)
print(numpy.concatenate((arr1,arr2),axis=0))


4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [7]:
# Function 5: Zeros and ones

import numpy
num=list(map(int,input().split()))
print(numpy.zeros(num,dtype=numpy.int))
print(numpy.ones(num,dtype=numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [8]:
# Function 6: Eye and Identity

import numpy
N,M=list(map(int,input().split()))
numpy.set_printoptions(sign=' ')
print(numpy.eye(N,M))


3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [9]:
# Function 7: Array Mathematics

import numpy
N,M=list(map(int,input().split()))
A=numpy.array([input().split() for _ in range(N)],int)
B=numpy.array([input().split() for _ in range(N)],int)
print(numpy.add(A,B))
print(numpy.subtract(A,B))
print(numpy.multiply(A,B))
print(A//B)
print(numpy.mod(A,B))
print(numpy.power(A,B))

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


In [10]:
# Function 8: Floor , ceil and Rint

import numpy
arr=input().strip().split(' ')
a=numpy.array(arr,float)
numpy.set_printoptions(sign=' ')
print(numpy.floor(a))
print(numpy.ceil(a))
print(numpy.rint(a))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [11]:
# Function 9: Sum and Prod

import numpy
N,M = list(map(int,input().split()))
arr=numpy.array([input().split() for _ in range(N)],int)
print(numpy.prod(numpy.sum(arr,axis=0),axis=0))


2 2
1 2
3 4
24


In [12]:
# Function 10: Min and Max

import numpy
N,M=list(map(int,input().split()))
A=numpy.array([input().split() for _ in range(N)],int)
print(numpy.max(numpy.min(A,axis=1)))


4 2 
2 5 
3 7 
1 3 
4 0
3


In [13]:
# Function 11: Mean, var and std

import numpy
N,M=list(map(int,input().split()))
A=numpy.array([input().split() for _ in range(N)],int)
print(numpy.mean(A,axis=1))
print(numpy.var(A,axis=0))
print(numpy.std(A,axis=None))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.118033988749895


In [14]:
# Function 12: Dot and cross

import numpy
N=int(input())
A=numpy.array([input().split() for _ in range(N)],int)
B=numpy.array([input().split() for _ in range(N)],int)
print(numpy.dot(A,B))


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


In [15]:
# Function 13: Inner and Outer

import numpy
A=numpy.array(input().split(),int)
B=numpy.array(input().split(),int)
print(numpy.inner(A,B))
print(numpy.outer(A,B))

0 1
2 3
3
[[0 0]
 [2 3]]


In [16]:
# Function 14: Polynomials

import numpy
a=list(map(float,input().split()))
x=int(input())
print(numpy.polyval(a,x))


1.1 2 3
0
3.0


In [17]:
# Function 15: Linear Algebra

import numpy
n=int(input())
A=numpy.array([input().split() for _ in range(n)],float)
numpy.set_printoptions(sign=' ')
print(numpy.linalg.det(A))


2
1.1 1.1
1.1 1.1
0.0
